serialPort: /dev/ttyUSB0
criticalTemp: 80
devices:
  - id: 0
    fans: [1, 2]
    curve:
      10: 0
      40: 10
      50: 30
      55: 35
      60: 40
      65: 45
      66: 46
      67: 47
      68: 48
      69: 49
      70: 50
      80: 100
  - id: 1
    fans: [2, 3]
    curve:
      10: 0
      40: 10
      50: 30
      55: 35
      60: 40
      65: 45
      66: 46
      67: 47
      68: 48
      69: 49
      70: 50
      80: 100
